services:
  nginx-front:
    image: nginx:1.17.8
    restart: always
    links:
      - nginx-back
    volumes:
      - ./code-front:/code
      - ./docker/nginx/nginx-front.conf:/etc/nginx/conf.d/nginx-front.conf
    ports:
      - "81:80"
    networks:
      net:
        ipv4_address: 192.168.240.2
  nginx-back:
    image: nginx:1.17.8
    restart: always
    links:
      - php-back
    volumes:
      - ./code-back:/code
      - ./docker/nginx/nginx-back.conf:/etc/nginx/conf.d/nginx-back.conf
    networks:
      net:
        ipv4_address: 192.168.240.3
  php-back:
    build:
      context: ./docker/php
    restart: always
    links:
      - mysql
    volumes:
      - ./code-back:/code
    networks:
      net:
        ipv4_address: 192.168.240.4
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/volume/mysql:/var/lib/mysql
    networks:
      net:
        ipv4_address: 192.168.240.5
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.240.0/24
